USE book_project;

INSERT INTO genre VALUES(1, '10th Century');
INSERT INTO genre VALUES(2, '11th Century');
INSERT INTO genre VALUES(3, '12th Century');
INSERT INTO genre VALUES(4, '13th Century');
INSERT INTO genre VALUES(5, '14th Century');
INSERT INTO genre VALUES(6, '15th Century');
INSERT INTO genre VALUES(7, '16th Century');
INSERT INTO genre VALUES(8, '17th Century');
INSERT INTO genre VALUES(9, '18th Century');
INSERT INTO genre VALUES(10, '19th Century');
INSERT INTO genre VALUES(11, '1st Grade');
INSERT INTO genre VALUES(12, '20th Century');
INSERT INTO genre VALUES(13, '21st Century');
INSERT INTO genre VALUES(14, '2nd Grade');
INSERT INTO genre VALUES(15, '40k');
INSERT INTO genre VALUES(16, 'Abuse');
INSERT INTO genre VALUES(17, 'Academia');
INSERT INTO genre VALUES(18, 'Academic');
INSERT INTO genre VALUES(19, 'Academics');
INSERT INTO genre VALUES(20, 'Action');
INSERT INTO genre VALUES(21, 'Activism');
INSERT INTO genre VALUES(22, 'Adoption');
INSERT INTO genre VALUES(23, 'Adult Fiction');
INSERT INTO genre VALUES(24, 'Adult');
INSERT INTO genre VALUES(25, 'Adventure');
INSERT INTO genre VALUES(26, 'Aeroplanes');
INSERT INTO genre VALUES(27, 'Africa');
INSERT INTO genre VALUES(28, 'African American Literature');
INSERT INTO genre VALUES(29, 'African American Romance');
INSERT INTO genre VALUES(30, 'African American');
INSERT INTO genre VALUES(31, 'African Literature');
INSERT INTO genre VALUES(32, 'Agriculture');
INSERT INTO genre VALUES(33, 'Airships');
INSERT INTO genre VALUES(34, 'Albanian Literature');
INSERT INTO genre VALUES(35, 'Alchemy');
INSERT INTO genre VALUES(36, 'Alcohol');
INSERT INTO genre VALUES(37, 'Algebra');
INSERT INTO genre VALUES(38, 'Algeria');
INSERT INTO genre VALUES(39, 'Algorithms');
INSERT INTO genre VALUES(40, 'Aliens');
INSERT INTO genre VALUES(41, 'Alternate History');
INSERT INTO genre VALUES(42, 'Alternate Universe');
INSERT INTO genre VALUES(43, 'Alternative Medicine');
INSERT INTO genre VALUES(44, 'Amateur Sleuth');
INSERT INTO genre VALUES(45, 'Amazon');
INSERT INTO genre VALUES(46, 'American Civil War');
INSERT INTO genre VALUES(47, 'American Classics');
INSERT INTO genre VALUES(48, 'American Fiction');
INSERT INTO genre VALUES(49, 'American History');
INSERT INTO genre VALUES(50, 'American Revolution');
INSERT INTO genre VALUES(51, 'American Revolutionary War');
INSERT INTO genre VALUES(52, 'American');
INSERT INTO genre VALUES(53, 'Americana');
INSERT INTO genre VALUES(54, 'Amish Fiction');
INSERT INTO genre VALUES(55, 'Amish');
INSERT INTO genre VALUES(56, 'Anarchism');
INSERT INTO genre VALUES(57, 'Ancient History');
INSERT INTO genre VALUES(58, 'Ancient');
INSERT INTO genre VALUES(59, 'Angels');
INSERT INTO genre VALUES(60, 'Anglo Saxon');
INSERT INTO genre VALUES(61, 'Animal Fiction');
INSERT INTO genre VALUES(62, 'Animals');
INSERT INTO genre VALUES(63, 'Anime');
INSERT INTO genre VALUES(64, 'Anthologies');
INSERT INTO genre VALUES(65, 'Anthropology');
INSERT INTO genre VALUES(66, 'Anthropomorphic');
INSERT INTO genre VALUES(67, 'Anti Intellectualism');
INSERT INTO genre VALUES(68, 'Anti Racist');
INSERT INTO genre VALUES(69, 'Apocalyptic');
INSERT INTO genre VALUES(70, 'Apple');
INSERT INTO genre VALUES(71, 'Archaeology');
INSERT INTO genre VALUES(72, 'Architecture');
INSERT INTO genre VALUES(73, 'Art Design');
INSERT INTO genre VALUES(74, 'Art History');
INSERT INTO genre VALUES(75, 'Art and Photography');
INSERT INTO genre VALUES(76, 'Art');
INSERT INTO genre VALUES(77, 'Arthurian');
INSERT INTO genre VALUES(78, 'Artificial Intelligence');
INSERT INTO genre VALUES(79, 'Asexual');
INSERT INTO genre VALUES(80, 'Asia');
INSERT INTO genre VALUES(81, 'Asian Literature');
INSERT INTO genre VALUES(82, 'Aspergers');
INSERT INTO genre VALUES(83, 'Astrology');
INSERT INTO genre VALUES(84, 'Astronomy');
INSERT INTO genre VALUES(85, 'Atheism');
INSERT INTO genre VALUES(86, 'Atlases');
INSERT INTO genre VALUES(87, 'Audiobook');
INSERT INTO genre VALUES(88, 'Australia');
INSERT INTO genre VALUES(89, 'Autobiography');
INSERT INTO genre VALUES(90, 'Aviation');
INSERT INTO genre VALUES(91, 'Babylon 5');
INSERT INTO genre VALUES(92, 'Back To School');
INSERT INTO genre VALUES(93, 'Baha I');
INSERT INTO genre VALUES(94, 'Bande Dessinée');
INSERT INTO genre VALUES(95, 'Bangladesh');
INSERT INTO genre VALUES(96, 'Banking');
INSERT INTO genre VALUES(97, 'Banks');
INSERT INTO genre VALUES(98, 'Banned Books');
INSERT INTO genre VALUES(99, 'Baseball');
INSERT INTO genre VALUES(100, 'Basketball');
INSERT INTO genre VALUES(101, 'Batman');
INSERT INTO genre VALUES(102, 'Battle Of Britain');
INSERT INTO genre VALUES(103, 'Battle Of Gettysburg');
INSERT INTO genre VALUES(104, 'Beauty and The Beast');
INSERT INTO genre VALUES(105, 'Beer');
INSERT INTO genre VALUES(106, 'Belgian');
INSERT INTO genre VALUES(107, 'Belgium');
INSERT INTO genre VALUES(108, 'Belief');
INSERT INTO genre VALUES(109, 'Benin');
INSERT INTO genre VALUES(110, 'Biblical Fiction');
INSERT INTO genre VALUES(111, 'Biblical');
INSERT INTO genre VALUES(112, 'Bicycles');
INSERT INTO genre VALUES(113, 'Biography Memoir');
INSERT INTO genre VALUES(114, 'Biography');
INSERT INTO genre VALUES(115, 'Biology');
INSERT INTO genre VALUES(116, 'Birds');
INSERT INTO genre VALUES(117, 'Bisexual');
INSERT INTO genre VALUES(118, 'Bizarro Fiction');
INSERT INTO genre VALUES(119, 'Black Literature');
INSERT INTO genre VALUES(120, 'Boarding School');
INSERT INTO genre VALUES(121, 'Bolivia');
INSERT INTO genre VALUES(122, 'Book Club');
INSERT INTO genre VALUES(123, 'Books About Books');
INSERT INTO genre VALUES(124, 'Booze');
INSERT INTO genre VALUES(125, 'Botswana');
INSERT INTO genre VALUES(126, 'Boys Love');
INSERT INTO genre VALUES(127, 'Brain');
INSERT INTO genre VALUES(128, 'Brazil');
INSERT INTO genre VALUES(129, 'Brewing');
INSERT INTO genre VALUES(130, 'British Literature');
INSERT INTO genre VALUES(131, 'Buddhism');
INSERT INTO genre VALUES(132, 'Buffy The Vampire Slayer');
INSERT INTO genre VALUES(133, 'Buisness');
INSERT INTO genre VALUES(134, 'Bulgaria');
INSERT INTO genre VALUES(135, 'Bulgarian Literature');
INSERT INTO genre VALUES(136, 'Burundi');
INSERT INTO genre VALUES(137, 'Buses');
INSERT INTO genre VALUES(138, 'Business');
INSERT INTO genre VALUES(139, 'Butch Femme');
INSERT INTO genre VALUES(140, 'Cameroon');
INSERT INTO genre VALUES(141, 'Canada');
INSERT INTO genre VALUES(142, 'Canadian Literature');
INSERT INTO genre VALUES(143, 'Canon');
INSERT INTO genre VALUES(144, 'Cars');
INSERT INTO genre VALUES(145, 'Cartography');
INSERT INTO genre VALUES(146, 'Cartoon');
INSERT INTO genre VALUES(147, 'Category Romance');
INSERT INTO genre VALUES(148, 'Catholic');
INSERT INTO genre VALUES(149, 'Cats');
INSERT INTO genre VALUES(150, 'Central Africa');
INSERT INTO genre VALUES(151, 'Chapter Books');
INSERT INTO genre VALUES(152, 'Chemistry');
INSERT INTO genre VALUES(153, 'Chess');
INSERT INTO genre VALUES(154, 'Chick Lit');
INSERT INTO genre VALUES(155, 'Childrens Classics');
INSERT INTO genre VALUES(156, 'Childrens');
INSERT INTO genre VALUES(157, 'China');
INSERT INTO genre VALUES(158, 'Chinese Literature');
INSERT INTO genre VALUES(159, 'Choose Your Own Adventure');
INSERT INTO genre VALUES(160, 'Christian Contemporary Fiction');
INSERT INTO genre VALUES(161, 'Christian Fantasy');
INSERT INTO genre VALUES(162, 'Christian Fiction');
INSERT INTO genre VALUES(163, 'Christian Historical Fiction');
INSERT INTO genre VALUES(164, 'Christian Living');
INSERT INTO genre VALUES(165, 'Christian Non Fiction');
INSERT INTO genre VALUES(166, 'Christian Romance');
INSERT INTO genre VALUES(167, 'Christian');
INSERT INTO genre VALUES(168, 'Christianity');
INSERT INTO genre VALUES(169, 'Christmas');
INSERT INTO genre VALUES(170, 'Church History');
INSERT INTO genre VALUES(171, 'Church');
INSERT INTO genre VALUES(172, 'Cinderella');
INSERT INTO genre VALUES(173, 'Cities');
INSERT INTO genre VALUES(174, 'Civil War Eastern Theater');
INSERT INTO genre VALUES(175, 'Civil War History');
INSERT INTO genre VALUES(176, 'Civil War');
INSERT INTO genre VALUES(177, 'Class');
INSERT INTO genre VALUES(178, 'Classic Literature');
INSERT INTO genre VALUES(179, 'Classical Music');
INSERT INTO genre VALUES(180, 'Classical Studies');
INSERT INTO genre VALUES(181, 'Classics');
INSERT INTO genre VALUES(182, 'Clean Romance');
INSERT INTO genre VALUES(183, 'Climate Change Fiction');
INSERT INTO genre VALUES(184, 'Climate Change');
INSERT INTO genre VALUES(185, 'Climbing');
INSERT INTO genre VALUES(186, 'Cocktails');
INSERT INTO genre VALUES(187, 'Coding');
INSERT INTO genre VALUES(188, 'Collections');
INSERT INTO genre VALUES(189, 'College');
INSERT INTO genre VALUES(190, 'Comedian');
INSERT INTO genre VALUES(191, 'Comedy');
INSERT INTO genre VALUES(192, 'Comic Book');
INSERT INTO genre VALUES(193, 'Comic Fantasy');
INSERT INTO genre VALUES(194, 'Comic Strips');
INSERT INTO genre VALUES(195, 'Comics Bd');
INSERT INTO genre VALUES(196, 'Comics Manga');
INSERT INTO genre VALUES(197, 'Comics');
INSERT INTO genre VALUES(198, 'Coming Of Age');
INSERT INTO genre VALUES(199, 'Comix');
INSERT INTO genre VALUES(200, 'Communication');
INSERT INTO genre VALUES(201, 'Computer Science');
INSERT INTO genre VALUES(202, 'Computers');
INSERT INTO genre VALUES(203, 'Conservation');
INSERT INTO genre VALUES(204, 'Conspiracy Theories');
INSERT INTO genre VALUES(205, 'Contemporary Romance');
INSERT INTO genre VALUES(206, 'Contemporary');
INSERT INTO genre VALUES(207, 'Cookbooks');
INSERT INTO genre VALUES(208, 'Cooking');
INSERT INTO genre VALUES(209, 'Counselling');
INSERT INTO genre VALUES(210, 'Counter Culture');
INSERT INTO genre VALUES(211, 'Counting');
INSERT INTO genre VALUES(212, 'Cozy Mystery');
INSERT INTO genre VALUES(213, 'Crafts');
INSERT INTO genre VALUES(214, 'Creation Science');
INSERT INTO genre VALUES(215, 'Crime');
INSERT INTO genre VALUES(216, 'Criticism');
INSERT INTO genre VALUES(217, 'Cross Dressing');
INSERT INTO genre VALUES(218, 'Cryptids');
INSERT INTO genre VALUES(219, 'Cryptozoology');
INSERT INTO genre VALUES(220, 'Cthulhu Mythos');
INSERT INTO genre VALUES(221, 'Cuisine');
INSERT INTO genre VALUES(222, 'Culinary');
INSERT INTO genre VALUES(223, 'Cult Classics');
INSERT INTO genre VALUES(224, 'Cults');
INSERT INTO genre VALUES(225, 'Cultural Heritage');
INSERT INTO genre VALUES(226, 'Cultural Studies');
INSERT INTO genre VALUES(227, 'Cultural');
INSERT INTO genre VALUES(228, 'Cyberpunk');
INSERT INTO genre VALUES(229, 'Cycling');
INSERT INTO genre VALUES(230, 'Czech Literature');
INSERT INTO genre VALUES(231, 'Danish');
INSERT INTO genre VALUES(232, 'Dark Fantasy');
INSERT INTO genre VALUES(233, 'Dark');
INSERT INTO genre VALUES(234, 'Dc Comics');
INSERT INTO genre VALUES(235, 'Death');
INSERT INTO genre VALUES(236, 'Deception');
INSERT INTO genre VALUES(237, 'Demons');
INSERT INTO genre VALUES(238, 'Denmark');
INSERT INTO genre VALUES(239, 'Design');
INSERT INTO genre VALUES(240, 'Detective');
INSERT INTO genre VALUES(241, 'Diary');
INSERT INTO genre VALUES(242, 'Dictionaries');
INSERT INTO genre VALUES(243, 'Did Not Finish');
INSERT INTO genre VALUES(244, 'Diets');
INSERT INTO genre VALUES(245, 'Dinosaurs');
INSERT INTO genre VALUES(246, 'Disability Studies');
INSERT INTO genre VALUES(247, 'Disability');
INSERT INTO genre VALUES(248, 'Discipleship');
INSERT INTO genre VALUES(249, 'Disease');
INSERT INTO genre VALUES(250, 'Divination');
INSERT INTO genre VALUES(251, 'Divorce');
INSERT INTO genre VALUES(252, 'Doctor Who');
INSERT INTO genre VALUES(253, 'Doctors');
INSERT INTO genre VALUES(254, 'Dogs');
INSERT INTO genre VALUES(255, 'Dragonlance');
INSERT INTO genre VALUES(256, 'Dragons');
INSERT INTO genre VALUES(257, 'Drama');
INSERT INTO genre VALUES(258, 'Drawing');
INSERT INTO genre VALUES(259, 'Drinking');
INSERT INTO genre VALUES(260, 'Dungeons and Dragons');
INSERT INTO genre VALUES(261, 'Dutch Literature');
INSERT INTO genre VALUES(262, 'Dying Earth');
INSERT INTO genre VALUES(263, 'Dystopia');
INSERT INTO genre VALUES(264, 'Earth Sciences');
INSERT INTO genre VALUES(265, 'Eastern Africa');
INSERT INTO genre VALUES(266, 'Eastern Philosophy');
INSERT INTO genre VALUES(267, 'Ecclesiology');
INSERT INTO genre VALUES(268, 'Ecology');
INSERT INTO genre VALUES(269, 'Economics');
INSERT INTO genre VALUES(270, 'Education');
INSERT INTO genre VALUES(271, 'Edwardian');
INSERT INTO genre VALUES(272, 'Egypt');
INSERT INTO genre VALUES(273, 'Egyptian Literature');
INSERT INTO genre VALUES(274, 'Egyptology');
INSERT INTO genre VALUES(275, 'Electrical Engineering');
INSERT INTO genre VALUES(276, 'Elizabethan Period');
INSERT INTO genre VALUES(277, 'Elves');
INSERT INTO genre VALUES(278, 'Emergency Services');
INSERT INTO genre VALUES(279, 'Emotion');
INSERT INTO genre VALUES(280, 'Engineering');
INSERT INTO genre VALUES(281, 'English Literature');
INSERT INTO genre VALUES(282, 'Entrepreneurship');
INSERT INTO genre VALUES(283, 'Environment');
INSERT INTO genre VALUES(284, 'Epic Fantasy');
INSERT INTO genre VALUES(285, 'Epic Poetry');
INSERT INTO genre VALUES(286, 'Epic');
INSERT INTO genre VALUES(287, 'Eritrea');
INSERT INTO genre VALUES(288, 'Esoterica');
INSERT INTO genre VALUES(289, 'Esp');
INSERT INTO genre VALUES(290, 'Espionage');
INSERT INTO genre VALUES(291, 'Essays');
INSERT INTO genre VALUES(292, 'Ethiopia');
INSERT INTO genre VALUES(293, 'Ethnography');
INSERT INTO genre VALUES(294, 'European History');
INSERT INTO genre VALUES(295, 'European Literature');
INSERT INTO genre VALUES(296, 'Evangelism');
INSERT INTO genre VALUES(297, 'Evolution');
INSERT INTO genre VALUES(298, 'Fables');
INSERT INTO genre VALUES(299, 'Fae');
INSERT INTO genre VALUES(300, 'Fairies');
INSERT INTO genre VALUES(301, 'Fairy Tale Retellings');
INSERT INTO genre VALUES(302, 'Fairy Tales');
INSERT INTO genre VALUES(303, 'Faith');
INSERT INTO genre VALUES(304, 'Family');
INSERT INTO genre VALUES(305, 'Fandom');
INSERT INTO genre VALUES(306, 'Fantasy Of Manners');
INSERT INTO genre VALUES(307, 'Fantasy Romance');
INSERT INTO genre VALUES(308, 'Fantasy');
INSERT INTO genre VALUES(309, 'Far Right');
INSERT INTO genre VALUES(310, 'Fashion');
INSERT INTO genre VALUES(311, 'Fat Acceptance');
INSERT INTO genre VALUES(312, 'Fat Studies');
INSERT INTO genre VALUES(313, 'Fat');
INSERT INTO genre VALUES(314, 'Female Authors');
INSERT INTO genre VALUES(315, 'Feminism');
INSERT INTO genre VALUES(316, 'Feminist Theory');
INSERT INTO genre VALUES(317, 'Fiction');
INSERT INTO genre VALUES(318, 'Field Guides');
INSERT INTO genre VALUES(319, 'Fighters');
INSERT INTO genre VALUES(320, 'Figure Skating');
INSERT INTO genre VALUES(321, 'Film');
INSERT INTO genre VALUES(322, 'Finance');
INSERT INTO genre VALUES(323, 'Finnish Literature');
INSERT INTO genre VALUES(324, 'Fire Services');
INSERT INTO genre VALUES(325, 'Firefighters');
INSERT INTO genre VALUES(326, 'Fitness');
INSERT INTO genre VALUES(327, 'Folk Tales');
INSERT INTO genre VALUES(328, 'Folklore');
INSERT INTO genre VALUES(329, 'Food History');
INSERT INTO genre VALUES(330, 'Food Preservation');
INSERT INTO genre VALUES(331, 'Food Writing');
INSERT INTO genre VALUES(332, 'Food and Drink');
INSERT INTO genre VALUES(333, 'Food');
INSERT INTO genre VALUES(334, 'Foodie');
INSERT INTO genre VALUES(335, 'Football');
INSERT INTO genre VALUES(336, 'Forgotten Realms');
INSERT INTO genre VALUES(337, 'Foster Parents');
INSERT INTO genre VALUES(338, 'Fostering');
INSERT INTO genre VALUES(339, 'Fractured Fairy Tales');
INSERT INTO genre VALUES(340, 'France');
INSERT INTO genre VALUES(341, 'French Literature');
INSERT INTO genre VALUES(342, 'French Revolution');
INSERT INTO genre VALUES(343, 'Frugal');
INSERT INTO genre VALUES(344, 'Fundamentalism');
INSERT INTO genre VALUES(345, 'Futurism');
INSERT INTO genre VALUES(346, 'Futuristic Romance');
INSERT INTO genre VALUES(347, 'Futuristic');
INSERT INTO genre VALUES(348, 'Game Design');
INSERT INTO genre VALUES(349, 'Gamebooks');
INSERT INTO genre VALUES(350, 'Games');
INSERT INTO genre VALUES(351, 'Gaming');
INSERT INTO genre VALUES(352, 'Gardening');
INSERT INTO genre VALUES(353, 'Gastronomy');
INSERT INTO genre VALUES(354, 'Gay Fiction');
INSERT INTO genre VALUES(355, 'Gay For You');
INSERT INTO genre VALUES(356, 'Gay');
INSERT INTO genre VALUES(357, 'Geek');
INSERT INTO genre VALUES(358, 'Gender Studies');
INSERT INTO genre VALUES(359, 'Gender and Sexuality');
INSERT INTO genre VALUES(360, 'Gender');
INSERT INTO genre VALUES(361, 'Genderqueer');
INSERT INTO genre VALUES(362, 'Genetics');
INSERT INTO genre VALUES(363, 'Geoffrey Chaucer');
INSERT INTO genre VALUES(364, 'Geography');
INSERT INTO genre VALUES(365, 'Geology');
INSERT INTO genre VALUES(366, 'Geometry');
INSERT INTO genre VALUES(367, 'Georgian Romance');
INSERT INTO genre VALUES(368, 'Georgian');
INSERT INTO genre VALUES(369, 'German Literature');
INSERT INTO genre VALUES(370, 'Germany');
INSERT INTO genre VALUES(371, 'Ghana');
INSERT INTO genre VALUES(372, 'Ghost Stories');
INSERT INTO genre VALUES(373, 'Ghosts');
INSERT INTO genre VALUES(374, 'Global Warming');
INSERT INTO genre VALUES(375, 'Go');
INSERT INTO genre VALUES(376, 'God');
INSERT INTO genre VALUES(377, 'Goddess');
INSERT INTO genre VALUES(378, 'Gods');
INSERT INTO genre VALUES(379, 'Golden Age Mystery');
INSERT INTO genre VALUES(380, 'Google');
INSERT INTO genre VALUES(381, 'Goth');
INSERT INTO genre VALUES(382, 'Gothic Horror');
INSERT INTO genre VALUES(383, 'Gothic Romance');
INSERT INTO genre VALUES(384, 'Gothic');
INSERT INTO genre VALUES(385, 'Government');
INSERT INTO genre VALUES(386, 'Grad School');
INSERT INTO genre VALUES(387, 'Graffiti');
INSERT INTO genre VALUES(388, 'Graphic Novels Comics Manga');
INSERT INTO genre VALUES(389, 'Graphic Novels Comics');
INSERT INTO genre VALUES(390, 'Graphic Novels Manga');
INSERT INTO genre VALUES(391, 'Graphic Novels');
INSERT INTO genre VALUES(392, 'Greece');
INSERT INTO genre VALUES(393, 'Greek Mythology');
INSERT INTO genre VALUES(394, 'Green');
INSERT INTO genre VALUES(395, 'Growth Mindset');
INSERT INTO genre VALUES(396, 'Guides');
INSERT INTO genre VALUES(397, 'Guinea');
INSERT INTO genre VALUES(398, 'Hackers');
INSERT INTO genre VALUES(399, 'Halloween');
INSERT INTO genre VALUES(400, 'Hard Boiled');
INSERT INTO genre VALUES(401, 'Hard Science Fiction');
INSERT INTO genre VALUES(402, 'Harem');
INSERT INTO genre VALUES(403, 'Harlequin Blaze');
INSERT INTO genre VALUES(404, 'Harlequin Desire');
INSERT INTO genre VALUES(405, 'Harlequin Heartwarming');
INSERT INTO genre VALUES(406, 'Harlequin Historical');
INSERT INTO genre VALUES(407, 'Harlequin Nocturne');
INSERT INTO genre VALUES(408, 'Harlequin Presents');
INSERT INTO genre VALUES(409, 'Harlequin Romance');
INSERT INTO genre VALUES(410, 'Harlequin Teen');
INSERT INTO genre VALUES(411, 'Harlequin');
INSERT INTO genre VALUES(412, 'Health Care');
INSERT INTO genre VALUES(413, 'Health');
INSERT INTO genre VALUES(414, 'Helicopters');
INSERT INTO genre VALUES(415, 'Herbs');
INSERT INTO genre VALUES(416, 'Heroic Fantasy');
INSERT INTO genre VALUES(417, 'High Fantasy');
INSERT INTO genre VALUES(418, 'High School');
INSERT INTO genre VALUES(419, 'Hinduism');
INSERT INTO genre VALUES(420, 'Hip Hop');
INSERT INTO genre VALUES(421, 'Historical Fantasy');
INSERT INTO genre VALUES(422, 'Historical Fiction');
INSERT INTO genre VALUES(423, 'Historical Mystery');
INSERT INTO genre VALUES(424, 'Historical Romance');
INSERT INTO genre VALUES(425, 'Historical');
INSERT INTO genre VALUES(426, 'History Of Medicine');
INSERT INTO genre VALUES(427, 'History Of Science');
INSERT INTO genre VALUES(428, 'History and Politics');
INSERT INTO genre VALUES(429, 'History');
INSERT INTO genre VALUES(430, 'Hockey');
INSERT INTO genre VALUES(431, 'Holiday');
INSERT INTO genre VALUES(432, 'Holland');
INSERT INTO genre VALUES(433, 'Holocaust');
INSERT INTO genre VALUES(434, 'Homeschool');
INSERT INTO genre VALUES(435, 'Horror');
INSERT INTO genre VALUES(436, 'Horse Racing');
INSERT INTO genre VALUES(437, 'Horses');
INSERT INTO genre VALUES(438, 'Horticulture');
INSERT INTO genre VALUES(439, 'How To');
INSERT INTO genre VALUES(440, 'Hqn');
INSERT INTO genre VALUES(441, 'Hugo Awards');
INSERT INTO genre VALUES(442, 'Human Development');
INSERT INTO genre VALUES(443, 'Human Resources');
INSERT INTO genre VALUES(444, 'Humanities');
INSERT INTO genre VALUES(445, 'Humor');
INSERT INTO genre VALUES(446, 'Hungarian Literature');
INSERT INTO genre VALUES(447, 'Hungary');
INSERT INTO genre VALUES(448, 'Illness');
INSERT INTO genre VALUES(449, 'India');
INSERT INTO genre VALUES(450, 'Indian Literature');
INSERT INTO genre VALUES(451, 'Indonesian Literature');
INSERT INTO genre VALUES(452, 'Information Science');
INSERT INTO genre VALUES(453, 'Inspirational');
INSERT INTO genre VALUES(454, 'Intelligent Design');
INSERT INTO genre VALUES(455, 'International Development');
INSERT INTO genre VALUES(456, 'International Literature');
INSERT INTO genre VALUES(457, 'International Relations');
INSERT INTO genre VALUES(458, 'International');
INSERT INTO genre VALUES(459, 'Internet');
INSERT INTO genre VALUES(460, 'Interracial Romance');
INSERT INTO genre VALUES(461, 'Intersex');
INSERT INTO genre VALUES(462, 'Iran');
INSERT INTO genre VALUES(463, 'Ireland');
INSERT INTO genre VALUES(464, 'Irish Literature');
INSERT INTO genre VALUES(465, 'Islam');
INSERT INTO genre VALUES(466, 'Israel');
INSERT INTO genre VALUES(467, 'Italian Literature');
INSERT INTO genre VALUES(468, 'Italy');
INSERT INTO genre VALUES(469, 'Ivory Coast');
INSERT INTO genre VALUES(470, 'Japan');
INSERT INTO genre VALUES(471, 'Japanese History');
INSERT INTO genre VALUES(472, 'Japanese Literature');
INSERT INTO genre VALUES(473, 'Jazz');
INSERT INTO genre VALUES(474, 'Jewellery');
INSERT INTO genre VALUES(475, 'Jewish');
INSERT INTO genre VALUES(476, 'Jokes');
INSERT INTO genre VALUES(477, 'Josei');
INSERT INTO genre VALUES(478, 'Journal');
INSERT INTO genre VALUES(479, 'Journaling');
INSERT INTO genre VALUES(480, 'Journalism');
INSERT INTO genre VALUES(481, 'Judaica');
INSERT INTO genre VALUES(482, 'Judaism');
INSERT INTO genre VALUES(483, 'Juvenile');
INSERT INTO genre VALUES(484, 'Kazakhstan');
INSERT INTO genre VALUES(485, 'Kenya');
INSERT INTO genre VALUES(486, 'Kids');
INSERT INTO genre VALUES(487, 'Knitting');
INSERT INTO genre VALUES(488, 'Komik');
INSERT INTO genre VALUES(489, 'LGBT');
INSERT INTO genre VALUES(490, 'Labor');
INSERT INTO genre VALUES(491, 'Language');
INSERT INTO genre VALUES(492, 'Latin American History');
INSERT INTO genre VALUES(493, 'Latin American Literature');
INSERT INTO genre VALUES(494, 'Latin American');
INSERT INTO genre VALUES(495, 'Law');
INSERT INTO genre VALUES(496, 'Lds Fiction');
INSERT INTO genre VALUES(497, 'Lds Non Fiction');
INSERT INTO genre VALUES(498, 'Lds');
INSERT INTO genre VALUES(499, 'Leadership');
INSERT INTO genre VALUES(500, 'Lebanon');
INSERT INTO genre VALUES(501, 'Led Zeppelin');
INSERT INTO genre VALUES(502, 'Legal Thriller');
INSERT INTO genre VALUES(503, 'Lenin');
INSERT INTO genre VALUES(504, 'Lesbian Fiction');
INSERT INTO genre VALUES(505, 'Lesbian Romance');
INSERT INTO genre VALUES(506, 'Lesbian');
INSERT INTO genre VALUES(507, 'Liberia');
INSERT INTO genre VALUES(508, 'Librarianship');
INSERT INTO genre VALUES(509, 'Library Science');
INSERT INTO genre VALUES(510, 'Libya');
INSERT INTO genre VALUES(511, 'Lie');
INSERT INTO genre VALUES(512, 'Light Novel');
INSERT INTO genre VALUES(513, 'Linguistics');
INSERT INTO genre VALUES(514, 'Literary Criticism');
INSERT INTO genre VALUES(515, 'Literary Fiction');
INSERT INTO genre VALUES(516, 'Literature');
INSERT INTO genre VALUES(517, 'Logic');
INSERT INTO genre VALUES(518, 'London Underground');
INSERT INTO genre VALUES(519, 'Love Inspired Historical');
INSERT INTO genre VALUES(520, 'Love Inspired Suspense');
INSERT INTO genre VALUES(521, 'Love Inspired');
INSERT INTO genre VALUES(522, 'Love Story');
INSERT INTO genre VALUES(523, 'Love');
INSERT INTO genre VALUES(524, 'Lovecraftian');
INSERT INTO genre VALUES(525, 'Loveswept');
INSERT INTO genre VALUES(526, 'Low Fantasy');
INSERT INTO genre VALUES(527, 'M F M');
INSERT INTO genre VALUES(528, 'M F Romance');
INSERT INTO genre VALUES(529, 'M M Contemporary');
INSERT INTO genre VALUES(530, 'M M F');
INSERT INTO genre VALUES(531, 'M M Fantasy');
INSERT INTO genre VALUES(532, 'M M Historical Romance');
INSERT INTO genre VALUES(533, 'M M M');
INSERT INTO genre VALUES(534, 'M M Mystery');
INSERT INTO genre VALUES(535, 'M M Paranormal');
INSERT INTO genre VALUES(536, 'M M Romance');
INSERT INTO genre VALUES(537, 'M M Science Fiction');
INSERT INTO genre VALUES(538, 'M M Sports Romance');
INSERT INTO genre VALUES(539, 'M M Young Adult');
INSERT INTO genre VALUES(540, 'Magic');
INSERT INTO genre VALUES(541, 'Magical Realism');
INSERT INTO genre VALUES(542, 'Magick');
INSERT INTO genre VALUES(543, 'Mail Order Brides');
INSERT INTO genre VALUES(544, 'Malawi');
INSERT INTO genre VALUES(545, 'Mali');
INSERT INTO genre VALUES(546, 'Management');
INSERT INTO genre VALUES(547, 'Manga Romance');
INSERT INTO genre VALUES(548, 'Manga');
INSERT INTO genre VALUES(549, 'Manhwa');
INSERT INTO genre VALUES(550, 'Maps');
INSERT INTO genre VALUES(551, 'Marathi');
INSERT INTO genre VALUES(552, 'Maritime');
INSERT INTO genre VALUES(553, 'Marriage');
INSERT INTO genre VALUES(554, 'Martial Arts');
INSERT INTO genre VALUES(555, 'Marvel');
INSERT INTO genre VALUES(556, 'Mary Shelley');
INSERT INTO genre VALUES(557, 'Mathematics');
INSERT INTO genre VALUES(558, 'Media Tie In');
INSERT INTO genre VALUES(559, 'Medical');
INSERT INTO genre VALUES(560, 'Medicine');
INSERT INTO genre VALUES(561, 'Medieval History');
INSERT INTO genre VALUES(562, 'Medieval Romance');
INSERT INTO genre VALUES(563, 'Medieval');
INSERT INTO genre VALUES(564, 'Memoir');
INSERT INTO genre VALUES(565, 'Menage');
INSERT INTO genre VALUES(566, 'Mental Health');
INSERT INTO genre VALUES(567, 'Mental Illness');
INSERT INTO genre VALUES(568, 'Mermaids');
INSERT INTO genre VALUES(569, 'Metaphysics');
INSERT INTO genre VALUES(570, 'Microhistory');
INSERT INTO genre VALUES(571, 'Middle Grade');
INSERT INTO genre VALUES(572, 'Military Fiction');
INSERT INTO genre VALUES(573, 'Military History');
INSERT INTO genre VALUES(574, 'Military Romance');
INSERT INTO genre VALUES(575, 'Military Science Fiction');
INSERT INTO genre VALUES(576, 'Mills and Boon');
INSERT INTO genre VALUES(577, 'Mine');
INSERT INTO genre VALUES(578, 'Mira');
INSERT INTO genre VALUES(579, 'Mixed Martial Arts');
INSERT INTO genre VALUES(580, 'Modern Classics');
INSERT INTO genre VALUES(581, 'Modern');
INSERT INTO genre VALUES(582, 'Money Management');
INSERT INTO genre VALUES(583, 'Money');
INSERT INTO genre VALUES(584, 'Monsters');
INSERT INTO genre VALUES(585, 'Mormonism');
INSERT INTO genre VALUES(586, 'Moroccan');
INSERT INTO genre VALUES(587, 'Morocco');
INSERT INTO genre VALUES(588, 'Motorcycle');
INSERT INTO genre VALUES(589, 'Motorcycling');
INSERT INTO genre VALUES(590, 'Mountaineering');
INSERT INTO genre VALUES(591, 'Mozambique');
INSERT INTO genre VALUES(592, 'Multicultural Literature');
INSERT INTO genre VALUES(593, 'Murder Mystery');
INSERT INTO genre VALUES(594, 'Museology');
INSERT INTO genre VALUES(595, 'Museums');
INSERT INTO genre VALUES(596, 'Music Biography');
INSERT INTO genre VALUES(597, 'Music');
INSERT INTO genre VALUES(598, 'Musicals');
INSERT INTO genre VALUES(599, 'Musicians');
INSERT INTO genre VALUES(600, 'Muslimah');
INSERT INTO genre VALUES(601, 'Mystery Thriller');
INSERT INTO genre VALUES(602, 'Mystery');
INSERT INTO genre VALUES(603, 'Mysticism');
INSERT INTO genre VALUES(604, 'Mythology');
INSERT INTO genre VALUES(605, 'NSFW');
INSERT INTO genre VALUES(606, 'Namibia');
INSERT INTO genre VALUES(607, 'Native American History');
INSERT INTO genre VALUES(608, 'Native Americans');
INSERT INTO genre VALUES(609, 'Natural History');
INSERT INTO genre VALUES(610, 'Nature');
INSERT INTO genre VALUES(611, 'Naturopathy');
INSERT INTO genre VALUES(612, 'Naval Historical Fiction');
INSERT INTO genre VALUES(613, 'Naval History');
INSERT INTO genre VALUES(614, 'Nazi Party');
INSERT INTO genre VALUES(615, 'Near Future');
INSERT INTO genre VALUES(616, 'Nerd');
INSERT INTO genre VALUES(617, 'Neuroscience');
INSERT INTO genre VALUES(618, 'New Adult Romance');
INSERT INTO genre VALUES(619, 'New Adult');
INSERT INTO genre VALUES(620, 'New Age');
INSERT INTO genre VALUES(621, 'New Testament');
INSERT INTO genre VALUES(622, 'New Weird');
INSERT INTO genre VALUES(623, 'New York');
INSERT INTO genre VALUES(624, 'Nigeria');
INSERT INTO genre VALUES(625, 'Nobel Prize');
INSERT INTO genre VALUES(626, 'Noir');
INSERT INTO genre VALUES(627, 'Nonfiction');
INSERT INTO genre VALUES(628, 'Nordic Noir');
INSERT INTO genre VALUES(629, 'Norman');
INSERT INTO genre VALUES(630, 'Northern Africa');
INSERT INTO genre VALUES(631, 'Novella');
INSERT INTO genre VALUES(632, 'Novels');
INSERT INTO genre VALUES(633, 'Number');
INSERT INTO genre VALUES(634, 'Numerology');
INSERT INTO genre VALUES(635, 'Nursery Rhymes');
INSERT INTO genre VALUES(636, 'Nursing');
INSERT INTO genre VALUES(637, 'Nutrition');
INSERT INTO genre VALUES(638, 'Occult');
INSERT INTO genre VALUES(639, 'Old Testament');
INSERT INTO genre VALUES(640, 'Omegaverse');
INSERT INTO genre VALUES(641, 'Oral History');
INSERT INTO genre VALUES(642, 'Ornithology');
INSERT INTO genre VALUES(643, 'Outdoors');
INSERT INTO genre VALUES(644, 'Own');
INSERT INTO genre VALUES(645, 'Paganism');
INSERT INTO genre VALUES(646, 'Pakistan');
INSERT INTO genre VALUES(647, 'Palaeontology');
INSERT INTO genre VALUES(648, 'Paranormal Mystery');
INSERT INTO genre VALUES(649, 'Paranormal Romance');
INSERT INTO genre VALUES(650, 'Paranormal Urban Fantasy');
INSERT INTO genre VALUES(651, 'Paranormal');
INSERT INTO genre VALUES(652, 'Parenting');
INSERT INTO genre VALUES(653, 'Peak Oil');
INSERT INTO genre VALUES(654, 'Personal Development');
INSERT INTO genre VALUES(655, 'Personal Finance');
INSERT INTO genre VALUES(656, 'Philosophy');
INSERT INTO genre VALUES(657, 'Photography');
INSERT INTO genre VALUES(658, 'Physics');
INSERT INTO genre VALUES(659, 'Picture Books');
INSERT INTO genre VALUES(660, 'Pilots');
INSERT INTO genre VALUES(661, 'Pirates');
INSERT INTO genre VALUES(662, 'Planetary Romance');
INSERT INTO genre VALUES(663, 'Planets');
INSERT INTO genre VALUES(664, 'Plantagenet');
INSERT INTO genre VALUES(665, 'Plants');
INSERT INTO genre VALUES(666, 'Plays');
INSERT INTO genre VALUES(667, 'Plus Size');
INSERT INTO genre VALUES(668, 'Poetry Plays');
INSERT INTO genre VALUES(669, 'Poetry');
INSERT INTO genre VALUES(670, 'Poland');
INSERT INTO genre VALUES(671, 'Police');
INSERT INTO genre VALUES(672, 'Polish Literature');
INSERT INTO genre VALUES(673, 'Political Science');
INSERT INTO genre VALUES(674, 'Politics');
INSERT INTO genre VALUES(675, 'Polyamorous');
INSERT INTO genre VALUES(676, 'Polyamory');
INSERT INTO genre VALUES(677, 'Polygamy');
INSERT INTO genre VALUES(678, 'Pop Culture');
INSERT INTO genre VALUES(679, 'Popular Science');
INSERT INTO genre VALUES(680, 'Pornography');
INSERT INTO genre VALUES(681, 'Portugal');
INSERT INTO genre VALUES(682, 'Portuguese Literature');
INSERT INTO genre VALUES(683, 'Post Apocalyptic');
INSERT INTO genre VALUES(684, 'Post Colonial');
INSERT INTO genre VALUES(685, 'Poverty');
INSERT INTO genre VALUES(686, 'Prayer');
INSERT INTO genre VALUES(687, 'Pre K');
INSERT INTO genre VALUES(688, 'Pre Raphaelite');
INSERT INTO genre VALUES(689, 'Prehistoric');
INSERT INTO genre VALUES(690, 'Prehistory');
INSERT INTO genre VALUES(691, 'Presidents');
INSERT INTO genre VALUES(692, 'Princesses');
INSERT INTO genre VALUES(693, 'Productivity');
INSERT INTO genre VALUES(694, 'Professors');
INSERT INTO genre VALUES(695, 'Programming');
INSERT INTO genre VALUES(696, 'Prostitution');
INSERT INTO genre VALUES(697, 'Pseudoscience');
INSERT INTO genre VALUES(698, 'Psychiatry');
INSERT INTO genre VALUES(699, 'Psychoanalysis');
INSERT INTO genre VALUES(700, 'Psychological Thriller');
INSERT INTO genre VALUES(701, 'Psychology');
INSERT INTO genre VALUES(702, 'Pulp');
INSERT INTO genre VALUES(703, 'Punk');
INSERT INTO genre VALUES(704, 'Puzzles');
INSERT INTO genre VALUES(705, 'Quantum Mechanics');
INSERT INTO genre VALUES(706, 'Queer Lit');
INSERT INTO genre VALUES(707, 'Queer Studies');
INSERT INTO genre VALUES(708, 'Queer');
INSERT INTO genre VALUES(709, 'Quilting');
INSERT INTO genre VALUES(710, 'Rabbits');
INSERT INTO genre VALUES(711, 'Race');
INSERT INTO genre VALUES(712, 'Racing');
INSERT INTO genre VALUES(713, 'Railways');
INSERT INTO genre VALUES(714, 'Read For College');
INSERT INTO genre VALUES(715, 'Read For School');
INSERT INTO genre VALUES(716, 'Realistic Fiction');
INSERT INTO genre VALUES(717, 'Recreation');
INSERT INTO genre VALUES(718, 'Reference');
INSERT INTO genre VALUES(719, 'Regency Romance');
INSERT INTO genre VALUES(720, 'Regency');
INSERT INTO genre VALUES(721, 'Relationships');
INSERT INTO genre VALUES(722, 'Religion');
INSERT INTO genre VALUES(723, 'Reportage');
INSERT INTO genre VALUES(724, 'Republic Of The Congo');
INSERT INTO genre VALUES(725, 'Research');
INSERT INTO genre VALUES(726, 'Retellings');
INSERT INTO genre VALUES(727, 'Reverse Harem');
INSERT INTO genre VALUES(728, 'Road Trip');
INSERT INTO genre VALUES(729, 'Robots');
INSERT INTO genre VALUES(730, 'Rock N Roll');
INSERT INTO genre VALUES(731, 'Role Playing Games');
INSERT INTO genre VALUES(732, 'Roman Britain');
INSERT INTO genre VALUES(733, 'Roman');
INSERT INTO genre VALUES(734, 'Romance');
INSERT INTO genre VALUES(735, 'Romania');
INSERT INTO genre VALUES(736, 'Romanian Literature');
INSERT INTO genre VALUES(737, 'Romanovs');
INSERT INTO genre VALUES(738, 'Romantic Suspense');
INSERT INTO genre VALUES(739, 'Romantic');
INSERT INTO genre VALUES(740, 'Romanticism');
INSERT INTO genre VALUES(741, 'Russia');
INSERT INTO genre VALUES(742, 'Russian History');
INSERT INTO genre VALUES(743, 'Russian Literature');
INSERT INTO genre VALUES(744, 'Russian Revolution');
INSERT INTO genre VALUES(745, 'Rwanda');
INSERT INTO genre VALUES(746, 'Sao Tome and Principe');
INSERT INTO genre VALUES(747, 'Satanism');
INSERT INTO genre VALUES(748, 'Scandinavian Literature');
INSERT INTO genre VALUES(749, 'School Stories');
INSERT INTO genre VALUES(750, 'School');
INSERT INTO genre VALUES(751, 'Sci Fi Fantasy');
INSERT INTO genre VALUES(752, 'Science Fiction Fantasy');
INSERT INTO genre VALUES(753, 'Science Fiction Romance');
INSERT INTO genre VALUES(754, 'Science Fiction');
INSERT INTO genre VALUES(755, 'Science Nature');
INSERT INTO genre VALUES(756, 'Science');
INSERT INTO genre VALUES(757, 'Scotland');
INSERT INTO genre VALUES(758, 'Scripture');
INSERT INTO genre VALUES(759, 'Seinen');
INSERT INTO genre VALUES(760, 'Self Help');
INSERT INTO genre VALUES(761, 'Semiotics');
INSERT INTO genre VALUES(762, 'Senegal');
INSERT INTO genre VALUES(763, 'Sequential Art');
INSERT INTO genre VALUES(764, 'Serbian Literature');
INSERT INTO genre VALUES(765, 'Sewing');
INSERT INTO genre VALUES(766, 'Sex Work');
INSERT INTO genre VALUES(767, 'Sexuality');
INSERT INTO genre VALUES(768, 'Shapeshifters');
INSERT INTO genre VALUES(769, 'Shojo');
INSERT INTO genre VALUES(770, 'Shonen');
INSERT INTO genre VALUES(771, 'Short Stories');
INSERT INTO genre VALUES(772, 'Short Story Collection');
INSERT INTO genre VALUES(773, 'Shounen Ai');
INSERT INTO genre VALUES(774, 'Sierra Leone');
INSERT INTO genre VALUES(775, 'Silhouette');
INSERT INTO genre VALUES(776, 'Singularity');
INSERT INTO genre VALUES(777, 'Skepticism');
INSERT INTO genre VALUES(778, 'Slash Fiction');
INSERT INTO genre VALUES(779, 'Slice Of Life');
INSERT INTO genre VALUES(780, 'Soccer');
INSERT INTO genre VALUES(781, 'Social Change');
INSERT INTO genre VALUES(782, 'Social Issues');
INSERT INTO genre VALUES(783, 'Social Justice');
INSERT INTO genre VALUES(784, 'Social Media');
INSERT INTO genre VALUES(785, 'Social Movements');
INSERT INTO genre VALUES(786, 'Social Science');
INSERT INTO genre VALUES(787, 'Social Work');
INSERT INTO genre VALUES(788, 'Social');
INSERT INTO genre VALUES(789, 'Society');
INSERT INTO genre VALUES(790, 'Sociology');
INSERT INTO genre VALUES(791, 'Software');
INSERT INTO genre VALUES(792, 'Soldiers');
INSERT INTO genre VALUES(793, 'Somalia');
INSERT INTO genre VALUES(794, 'South Africa');
INSERT INTO genre VALUES(795, 'Southern Gothic');
INSERT INTO genre VALUES(796, 'Southern');
INSERT INTO genre VALUES(797, 'Soviet History');
INSERT INTO genre VALUES(798, 'Soviet Union');
INSERT INTO genre VALUES(799, 'Space Opera');
INSERT INTO genre VALUES(800, 'Space');
INSERT INTO genre VALUES(801, 'Spain');
INSERT INTO genre VALUES(802, 'Spanish Civil War');
INSERT INTO genre VALUES(803, 'Spanish History');
INSERT INTO genre VALUES(804, 'Spanish Literature');
INSERT INTO genre VALUES(805, 'Speculative Fiction');
INSERT INTO genre VALUES(806, 'Spider Man');
INSERT INTO genre VALUES(807, 'Spiritualism');
INSERT INTO genre VALUES(808, 'Spirituality');
INSERT INTO genre VALUES(809, 'Splatterpunk');
INSERT INTO genre VALUES(810, 'Sports Romance');
INSERT INTO genre VALUES(811, 'Sports');
INSERT INTO genre VALUES(812, 'Spy Thriller');
INSERT INTO genre VALUES(813, 'Stand Up');
INSERT INTO genre VALUES(814, 'Star Trek Deep Space Nine');
INSERT INTO genre VALUES(815, 'Star Trek Original Series');
INSERT INTO genre VALUES(816, 'Star Trek The Next Generation');
INSERT INTO genre VALUES(817, 'Star Trek Voyager');
INSERT INTO genre VALUES(818, 'Star Trek');
INSERT INTO genre VALUES(819, 'Star Wars');
INSERT INTO genre VALUES(820, 'Steampunk');
INSERT INTO genre VALUES(821, 'Storytime');
INSERT INTO genre VALUES(822, 'Street Art');
INSERT INTO genre VALUES(823, 'Strippers');
INSERT INTO genre VALUES(824, 'Stuart');
INSERT INTO genre VALUES(825, 'Students');
INSERT INTO genre VALUES(826, 'Sudan');
INSERT INTO genre VALUES(827, 'Superheroes');
INSERT INTO genre VALUES(828, 'Superman');
INSERT INTO genre VALUES(829, 'Supernatural Romance');
INSERT INTO genre VALUES(830, 'Supernatural');
INSERT INTO genre VALUES(831, 'Surreal');
INSERT INTO genre VALUES(832, 'Survival');
INSERT INTO genre VALUES(833, 'Suspense');
INSERT INTO genre VALUES(834, 'Sustainability');
INSERT INTO genre VALUES(835, 'Swashbuckling');
INSERT INTO genre VALUES(836, 'Sweden');
INSERT INTO genre VALUES(837, 'Swedish Literature');
INSERT INTO genre VALUES(838, 'Sword and Planet');
INSERT INTO genre VALUES(839, 'Sword and Sorcery');
INSERT INTO genre VALUES(840, 'Tanzania');
INSERT INTO genre VALUES(841, 'Taoism');
INSERT INTO genre VALUES(842, 'Tarot');
INSERT INTO genre VALUES(843, 'Tasmania');
INSERT INTO genre VALUES(844, 'Taxation');
INSERT INTO genre VALUES(845, 'Tea');
INSERT INTO genre VALUES(846, 'Teachers');
INSERT INTO genre VALUES(847, 'Teaching');
INSERT INTO genre VALUES(848, 'Technical');
INSERT INTO genre VALUES(849, 'Technology');
INSERT INTO genre VALUES(850, 'Teen');
INSERT INTO genre VALUES(851, 'Terrorism');
INSERT INTO genre VALUES(852, 'Textbooks');
INSERT INTO genre VALUES(853, 'The United States Of America');
INSERT INTO genre VALUES(854, 'The World');
INSERT INTO genre VALUES(855, 'Theatre');
INSERT INTO genre VALUES(856, 'Thelema');
INSERT INTO genre VALUES(857, 'Theology');
INSERT INTO genre VALUES(858, 'Theory');
INSERT INTO genre VALUES(859, 'Theosophy');
INSERT INTO genre VALUES(860, 'Thriller');
INSERT INTO genre VALUES(861, 'Time Travel Romance');
INSERT INTO genre VALUES(862, 'Time Travel');
INSERT INTO genre VALUES(863, 'Togo');
INSERT INTO genre VALUES(864, 'Traditional Chinese Medicine');
INSERT INTO genre VALUES(865, 'Traditional Regency');
INSERT INTO genre VALUES(866, 'Tragedy');
INSERT INTO genre VALUES(867, 'Trains');
INSERT INTO genre VALUES(868, 'Transgender');
INSERT INTO genre VALUES(869, 'Transport');
INSERT INTO genre VALUES(870, 'Travel');
INSERT INTO genre VALUES(871, 'Travelogue');
INSERT INTO genre VALUES(872, 'Trivia');
INSERT INTO genre VALUES(873, 'True Crime');
INSERT INTO genre VALUES(874, 'True Story');
INSERT INTO genre VALUES(875, 'Tudor Period');
INSERT INTO genre VALUES(876, 'Turkish Literature');
INSERT INTO genre VALUES(877, 'Turkish');
INSERT INTO genre VALUES(878, 'Tv');
INSERT INTO genre VALUES(879, 'Uganda');
INSERT INTO genre VALUES(880, 'Ukraine');
INSERT INTO genre VALUES(881, 'Ukrainian Literature');
INSERT INTO genre VALUES(882, 'Unfinished');
INSERT INTO genre VALUES(883, 'Unicorns');
INSERT INTO genre VALUES(884, 'United States');
INSERT INTO genre VALUES(885, 'Urban Fantasy');
INSERT INTO genre VALUES(886, 'Urban Planning');
INSERT INTO genre VALUES(887, 'Urban Studies');
INSERT INTO genre VALUES(888, 'Urban');
INSERT INTO genre VALUES(889, 'Urbanism');
INSERT INTO genre VALUES(890, 'Us Presidents');
INSERT INTO genre VALUES(891, 'Usability');
INSERT INTO genre VALUES(892, 'Utopia');
INSERT INTO genre VALUES(893, 'Vaccines');
INSERT INTO genre VALUES(894, 'Vampires');
INSERT INTO genre VALUES(895, 'Vegan');
INSERT INTO genre VALUES(896, 'Vegetarian');
INSERT INTO genre VALUES(897, 'Vegetarianism');
INSERT INTO genre VALUES(898, 'Victor Frankenstein');
INSERT INTO genre VALUES(899, 'Victorian Romance');
INSERT INTO genre VALUES(900, 'Victorian');
INSERT INTO genre VALUES(901, 'Video Games');
INSERT INTO genre VALUES(902, 'Viking Romance');
INSERT INTO genre VALUES(903, 'Virtual Reality');
INSERT INTO genre VALUES(904, 'Visual Art');
INSERT INTO genre VALUES(905, 'Walking');
INSERT INTO genre VALUES(906, 'War');
INSERT INTO genre VALUES(907, 'Warcraft');
INSERT INTO genre VALUES(908, 'Warriors');
INSERT INTO genre VALUES(909, 'Web');
INSERT INTO genre VALUES(910, 'Webcomic');
INSERT INTO genre VALUES(911, 'Website Design');
INSERT INTO genre VALUES(912, 'Weird Fiction');
INSERT INTO genre VALUES(913, 'Weird West');
INSERT INTO genre VALUES(914, 'Werewolves');
INSERT INTO genre VALUES(915, 'Western Africa');
INSERT INTO genre VALUES(916, 'Western Historical Romance');
INSERT INTO genre VALUES(917, 'Western Romance');
INSERT INTO genre VALUES(918, 'Westerns');
INSERT INTO genre VALUES(919, 'Whodunit');
INSERT INTO genre VALUES(920, 'Wicca');
INSERT INTO genre VALUES(921, 'Wilderness');
INSERT INTO genre VALUES(922, 'Wildlife');
INSERT INTO genre VALUES(923, 'Wine');
INSERT INTO genre VALUES(924, 'Witchcraft');
INSERT INTO genre VALUES(925, 'Witches');
INSERT INTO genre VALUES(926, 'Wizards');
INSERT INTO genre VALUES(927, 'Wolves');
INSERT INTO genre VALUES(928, 'Womens Fiction');
INSERT INTO genre VALUES(929, 'Womens Studies');
INSERT INTO genre VALUES(930, 'Womens');
INSERT INTO genre VALUES(931, 'Wonder Woman');
INSERT INTO genre VALUES(932, 'Woodwork');
INSERT INTO genre VALUES(933, 'Words');
INSERT INTO genre VALUES(934, 'World History');
INSERT INTO genre VALUES(935, 'World Of Darkness');
INSERT INTO genre VALUES(936, 'World Of Warcraft');
INSERT INTO genre VALUES(937, 'World War I');
INSERT INTO genre VALUES(938, 'World War II');
INSERT INTO genre VALUES(939, 'Writing');
INSERT INTO genre VALUES(940, 'X Men');
INSERT INTO genre VALUES(941, 'Yaoi');
INSERT INTO genre VALUES(942, 'Yeti');
INSERT INTO genre VALUES(943, 'Young Adult Contemporary');
INSERT INTO genre VALUES(944, 'Young Adult Fantasy');
INSERT INTO genre VALUES(945, 'Young Adult Historical Fiction');
INSERT INTO genre VALUES(946, 'Young Adult Paranormal');
INSERT INTO genre VALUES(947, 'Young Adult Romance');
INSERT INTO genre VALUES(948, 'Young Adult Science Fiction');
INSERT INTO genre VALUES(949, 'Young Adult');
INSERT INTO genre VALUES(950, 'Young Readers');
INSERT INTO genre VALUES(951, 'Yuri');
INSERT INTO genre VALUES(952, 'Zambia');
INSERT INTO genre VALUES(953, 'Zen');
INSERT INTO genre VALUES(954, 'Zimbabwe');
INSERT INTO genre VALUES(955, 'Zombies');
